# Generated by Django 3.2.24 on 2024-10-24 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='total',
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Disike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=300)),
                ('total', models.CharField(max_length=300)),
                ('POST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.post')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
