# Generated by Django 3.2.24 on 2024-10-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20241024_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='type',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
